// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_CanvasWidget.cpp"
#include "UVLADIE3JM/moc_MainWindow.cpp"
#include "UVLADIE3JM/moc_ShapeListWidget.cpp"
#include "UVLADIE3JM/moc_StatusBarWidget.cpp"
#include "UVLADIE3JM/moc_ToolbarWidget.cpp"
