#include "SnapManager.h"
#include "CanvasWidget.h"
#include "GeometryStore.h"
#include <cmath>

// ============================================================
// SnapManager implementation
// ============================================================

namespace {

// Local-space feature points of the unit primitives generated by
// GeometryFactory::create3DEdges/Faces — keep in sync with those:
//   cube half-extent 0.5 · cylinder r=1, z∈[-1,1] · cone r=1, apex z=+1,
//   base z=-1 · sphere r=1 (poles ±z) · torus R=1, r=0.4 (flat in XY).
// Everything is pushed through the shape's model matrix so position,
// rotation and scale are all honored.
void addSolidFeaturePoints(const BaseShape* shape, std::vector<SnapPoint>& out) {
    Mat4 m = Mat4::modelMatrix(shape->position, shape->rotation, shape->scale);
    auto add = [&](const Vec3& local, int type) {
        out.push_back({m.transformPoint(local), type, shape->id});
    };

    switch (shape->type) {
        case ShapeType::Cube: {
            const float h = 0.5f; // half extent of the unit cube
            for (int sx = -1; sx <= 1; sx += 2)
                for (int sy = -1; sy <= 1; sy += 2)
                    for (int sz = -1; sz <= 1; sz += 2)
                        add({h * sx, h * sy, h * sz}, 3);
            break;
        }
        case ShapeType::Cylinder: {
            add({0, 0, -1}, 1); // bottom cap center
            add({0, 0,  1}, 1); // top cap center
            // Rim quadrant points — endpoints of the drawn vertical edges
            for (int q = 0; q < 4; q++) {
                float a = M_PI_2 * q;
                float c = std::cos(a), s = std::sin(a);
                add({c, s, -1}, 3);
                add({c, s,  1}, 3);
            }
            break;
        }
        case ShapeType::Cone: {
            add({0, 0,  1}, 3); // apex
            add({0, 0, -1}, 1); // base center
            // Base rim quadrant points — endpoints of the drawn generators
            for (int q = 0; q < 4; q++) {
                float a = M_PI_2 * q;
                add({std::cos(a), std::sin(a), -1}, 3);
            }
            break;
        }
        case ShapeType::Sphere:
            add({0, 0,  0}, 1); // center
            add({0, 0, -1}, 3); // south pole
            add({0, 0,  1}, 3); // north pole
            break;

        case ShapeType::Torus: {
            add({0, 0, 0}, 1);
            const float R = 1.0f, r = 0.4f; // matches createTorusEdges
            for (int q = 0; q < 4; q++) {
                float a = M_PI_2 * q;
                float c = std::cos(a), s = std::sin(a);
                add({(R + r) * c, (R + r) * s, 0}, 3); // outer equator
                add({(R - r) * c, (R - r) * s, 0}, 3); // inner equator
            }
            break;
        }
        default:
            break;
    }
}

} // namespace

std::vector<SnapPoint> SnapManager::collectAllSnapPoints() {
    std::vector<SnapPoint> points;

    for (auto& shape : g_store.shapes) {
        if (!shape->visible) continue;

        if (shape->type == ShapeType::LineSegment) {
            auto* ls = static_cast<LineSegmentShape*>(shape.get());
            Vertex* sv = g_store.getVertexById(ls->startVertexId);
            Vertex* ev = g_store.getVertexById(ls->endVertexId);
            if (sv && ev) {
                points.push_back({sv->position, 0, ls->id});
                points.push_back({ev->position, 0, ls->id});
                Vec3 mid = {(sv->position.x + ev->position.x)/2,
                            (sv->position.y + ev->position.y)/2,
                            (sv->position.z + ev->position.z)/2};
                points.push_back({mid, 2, ls->id});
            }
        } else if (shape->type == ShapeType::CircularArc) {
            auto* arc = static_cast<CircularArcShape*>(shape.get());
            Vertex* cv = g_store.getVertexById(arc->centerVertexId);
            Vertex* sv = g_store.getVertexById(arc->startVertexId);
            Vertex* ev = g_store.getVertexById(arc->endVertexId);
            if (cv && sv && ev) {
                points.push_back({cv->position, 1, arc->id});
                points.push_back({sv->position, 0, arc->id});
                points.push_back({ev->position, 0, arc->id});
                Vec3 mid = {(sv->position.x + ev->position.x)/2,
                            (sv->position.y + ev->position.y)/2,
                            (sv->position.z + ev->position.z)/2};
                points.push_back({mid, 2, arc->id});
            }
        } else if (shape->type == ShapeType::Circle) {
            auto* circ = static_cast<CircleShape*>(shape.get());
            Vertex* c = g_store.getVertexById(circ->centerVertexId);
            if (c) points.push_back({c->position, 1, circ->id});
        } else if (shape->type == ShapeType::Rectangle ||
                   shape->type == ShapeType::Triangle ||
                   shape->type == ShapeType::Polygon) {
            std::vector<std::string> vertexIds;
            if (shape->type == ShapeType::Rectangle)
                vertexIds = static_cast<RectangleShape*>(shape.get())->vertexIds;
            else if (shape->type == ShapeType::Triangle)
                vertexIds = static_cast<TriangleShape*>(shape.get())->vertexIds;
            else
                vertexIds = static_cast<PolygonShape*>(shape.get())->vertexIds;
            for (auto& vid : vertexIds) {
                Vertex* v = g_store.getVertexById(vid);
                if (v) points.push_back({v->position, 3, shape->id});
            }
        } else {
            // 3D solid: feature points (corners, centers, apex, poles...)
            addSolidFeaturePoints(shape.get(), points);
        }
    }
    return points;
}

SnapManager::SnapResult SnapManager::findSnapPoint(const QPointF& screenPos, CanvasWidget* cv) {
    SnapResult result;
    // Fallback (nothing in range): the cursor mapped onto the y=0 work
    // plane — identical to the pre-snap behavior of every tool.
    result.snappedPosition = cv->screenToWorldOnWorkPlane(screenPos.x(), screenPos.y());
    result.snapped = false;
    result.snapType = -1;

    auto snapPoints = collectAllSnapPoints();

    float minDistSq = snapThreshold * snapThreshold;
    const SnapPoint* closest = nullptr;

    for (auto& sp : snapPoints) {
        QPointF p = cv->worldToScreen(sp.position);
        float dx = p.x() - screenPos.x();
        float dy = p.y() - screenPos.y();
        float distSq = dx * dx + dy * dy;
        if (distSq < minDistSq) {
            minDistSq = distSq;
            closest = &sp;
        }
    }

    if (closest) {
        result.snappedPosition = closest->position;
        result.snapped = true;
        result.snapType = closest->type;
    }

    return result;
}
